name: Github release tag

on:
  push:
    tags: ["v*"]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  gh-release:
    runs-on: ubuntu-22.04
    if: github.repository == 'Hdoc1509/vim-map-side.nvim'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Create release
        uses: softprops/action-gh-release@v2.3.3
        with:
          tag_name: ${{ github.ref_name }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md) for details.
          token: ${{ secrets.GITHUB_TOKEN }}
